language: python
python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8
dist: xenial

before_install:
- echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc

install:
- pip install -r requirements.txt
- pip install codecov
- pip install .
- python setup.py install

before_script:

script:
- coverage run metaboverse_cl/__test__.py
- coverage run metaboverse_cl/mapper/__test__.py
- coverage run metaboverse_cl/curate/__test__.py
- coverage run metaboverse_cl/analyze/__test__.py

#after_success:
#- codecov

#deploy:
#  provider: pypi
#  user: j-berg
#  password:
#    secure:
#  skip_existing: true
#  on:
#    tags: true
