language: python
python:
  - 3.6
  - 3.7
  - 3.8
dist: xenial

before_install:
- echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc

install: travis_wait 30 mvn install
- hash -d pip
- pip install -r requirements.txt
- pip install codecov
- pip install .
- python setup.py install

script:
- coverage run metaboverse_cli/__test__.py
- bash <(curl -s https://codecov.io/bash) -cF python
- coverage run metaboverse_cli/curate/__test__.py
- bash <(curl -s https://codecov.io/bash) -cF python
- coverage run metaboverse_cli/analyze/__test__.py
- bash <(curl -s https://codecov.io/bash) -cF python
# - coverage run metaboverse_cli/mapper/__test__.py # can't run due to travis memory limit

after_success:
