language: python
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
dist: xenial

before_install:
- echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc

install:
- pip install -r requirements.txt
- pip install codecov
- pip install .
- python setup.py install

before_script:

script:
- coverage run tests/__main__.py
#- coverage run -a tests/format_test.py

#after_success:
#- codecov

#deploy:
#  provider: pypi
#  user: j-berg
#  password:
#    secure:
#  skip_existing: true
#  on:
#    tags: true
